#!/usr/bin/env python3
"""
ETL Pipeline: Kaggle Dataset → PostgreSQL
==========================================
Generated by Senior Data Engineer Skill
Date: 2026-03-16

Usage:
    python3 etl_kaggle_to_postgres.py --dataset <kaggle-slug> [options]

Examples:
    python3 etl_kaggle_to_postgres.py --dataset blastchar/telco-customer-churn
    python3 etl_kaggle_to_postgres.py --dataset jessicali9530/kc-house-data --table houses
    python3 etl_kaggle_to_postgres.py --dataset /path/to/local/file.csv --table customers
"""

import argparse
import csv
import glob
import logging
import os
import re
import sys
import time
import zipfile
from datetime import datetime

import pandas as pd
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from sqlalchemy import create_engine, text

# ============================================================
# CONFIGURATION
# ============================================================
BASE_DIR = "/home/sindhuh/.openclaw/workspace/etl-pipeline"
DATA_DIR = os.path.join(BASE_DIR, "data")
LOG_DIR = os.path.join(BASE_DIR, "logs")
REPORT_DIR = "/home/sindhuh/.openclaw/workspace/reports"

DEFAULT_DB = "kaggle_data"
DEFAULT_HOST = "localhost"
DEFAULT_PORT = 5432
DEFAULT_USER = os.environ.get("PGUSER", "sindhuh")
DEFAULT_PASSWORD = os.environ.get("PGPASSWORD", "")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(os.path.join(LOG_DIR, "pipeline.log"), mode="a"),
    ],
)
logger = logging.getLogger("etl-pipeline")


# ============================================================
# PHASE 1: EXTRACT
# ============================================================
def extract_from_kaggle(dataset_slug: str) -> str:
    """Download dataset from Kaggle and return path to CSV."""
    logger.info(f"📥 EXTRACT: Downloading dataset '{dataset_slug}' from Kaggle...")

    # If it's a local file, skip download
    if os.path.isfile(dataset_slug):
        logger.info(f"📂 Using local file: {dataset_slug}")
        return dataset_slug

    os.makedirs(DATA_DIR, exist_ok=True)

    # Download via kaggle CLI
    cmd = f"kaggle datasets download -d {dataset_slug} -p {DATA_DIR} --unzip --force"
    logger.info(f"   Running: {cmd}")
    exit_code = os.system(cmd)

    if exit_code != 0:
        raise RuntimeError(f"Kaggle download failed with exit code {exit_code}")

    # Find the downloaded CSV(s)
    csv_files = glob.glob(os.path.join(DATA_DIR, "**/*.csv"), recursive=True)
    if not csv_files:
        # Check for zip files and extract
        zip_files = glob.glob(os.path.join(DATA_DIR, "*.zip"))
        for zf in zip_files:
            with zipfile.ZipFile(zf, "r") as z:
                z.extractall(DATA_DIR)
        csv_files = glob.glob(os.path.join(DATA_DIR, "**/*.csv"), recursive=True)

    if not csv_files:
        raise FileNotFoundError(f"No CSV files found after downloading {dataset_slug}")

    # Use the largest CSV if multiple
    csv_files.sort(key=os.path.getsize, reverse=True)
    selected = csv_files[0]
    logger.info(f"   Found {len(csv_files)} CSV file(s). Using: {selected}")
    logger.info(f"   Size: {os.path.getsize(selected) / 1024 / 1024:.2f} MB")

    return selected


# ============================================================
# PHASE 2: TRANSFORM
# ============================================================
def transform_data(df: pd.DataFrame, table_name: str) -> pd.DataFrame:
    """Clean and transform the dataframe."""
    logger.info(f"🔄 TRANSFORM: Processing {len(df)} rows × {len(df.columns)} columns...")
    start = time.time()

    original_shape = df.shape

    # 1. Normalize column names (lowercase, underscores, no special chars)
    df.columns = [
        re.sub(r"[^a-z0-9_]", "", col.lower().replace(" ", "_").replace("-", "_"))
        for col in df.columns
    ]
    # Remove leading/trailing underscores and double underscores
    df.columns = [re.sub(r"_+", "_", col).strip("_") for col in df.columns]
    logger.info(f"   ✅ Normalized {len(df.columns)} column names")

    # 2. Strip whitespace from string columns
    str_cols = df.select_dtypes(include=["object"]).columns
    for col in str_cols:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace({"nan": None, "None": None, "": None})
    logger.info(f"   ✅ Stripped whitespace from {len(str_cols)} string columns")

    # 3. Auto-detect and parse date columns
    date_cols_detected = []
    for col in str_cols:
        sample = df[col].dropna().head(100)
        if sample.empty:
            continue
        try:
            parsed = pd.to_datetime(sample, infer_datetime_format=True)
            if parsed.notna().sum() > len(sample) * 0.8:
                df[col] = pd.to_datetime(df[col], errors="coerce")
                date_cols_detected.append(col)
        except (ValueError, TypeError):
            pass
    if date_cols_detected:
        logger.info(f"   ✅ Auto-detected date columns: {date_cols_detected}")

    # 4. Optimize numeric types
    for col in df.select_dtypes(include=["float64"]).columns:
        if df[col].dropna().apply(lambda x: x == int(x) if pd.notna(x) else True).all():
            df[col] = df[col].astype("Int64")  # nullable integer
    logger.info(f"   ✅ Optimized numeric types")

    # 5. Remove completely empty rows
    before = len(df)
    df = df.dropna(how="all")
    dropped = before - len(df)
    if dropped:
        logger.info(f"   ✅ Dropped {dropped} completely empty rows")

    # 6. Remove exact duplicate rows
    before = len(df)
    df = df.drop_duplicates()
    deduped = before - len(df)
    if deduped:
        logger.info(f"   ✅ Removed {deduped} duplicate rows")

    elapsed = time.time() - start
    logger.info(
        f"   📊 Transform complete: {original_shape} → {df.shape} "
        f"({elapsed:.2f}s)"
    )

    return df


# ============================================================
# PHASE 3: QUALITY CHECKS
# ============================================================
def run_quality_checks(df: pd.DataFrame) -> dict:
    """Run data quality validation before loading."""
    logger.info("🔍 QUALITY: Running pre-load quality checks...")

    checks = []

    # Row count
    row_status = "PASS" if len(df) > 0 else "FAIL"
    checks.append({"check": "row_count", "status": row_status, "value": len(df)})

    # Null analysis per column
    null_summary = df.isnull().sum()
    high_null_cols = null_summary[null_summary > len(df) * 0.5]
    null_status = "WARN" if len(high_null_cols) > 0 else "PASS"
    checks.append({
        "check": "null_analysis",
        "status": null_status,
        "high_null_columns": high_null_cols.to_dict() if len(high_null_cols) > 0 else {},
        "total_nulls": int(null_summary.sum()),
    })

    # Duplicate check
    dup_count = df.duplicated().sum()
    dup_status = "PASS" if dup_count == 0 else "WARN"
    checks.append({"check": "duplicates", "status": dup_status, "count": int(dup_count)})

    # Column type summary
    type_summary = df.dtypes.astype(str).value_counts().to_dict()
    checks.append({"check": "type_summary", "status": "INFO", "types": type_summary})

    # Print results
    for c in checks:
        icon = {"PASS": "✅", "FAIL": "❌", "WARN": "⚠️", "INFO": "ℹ️"}.get(c["status"], "❓")
        logger.info(f"   {icon} {c['check']}: {c['status']}")

    overall = "PASS" if all(c["status"] in ("PASS", "INFO") for c in checks) else "WARN"
    logger.info(f"   📊 Quality overall: {overall}")

    return {"overall": overall, "checks": checks}


# ============================================================
# PHASE 4: LOAD
# ============================================================
def ensure_database(host, port, user, password, dbname):
    """Create the database if it doesn't exist."""
    try:
        conn = psycopg2.connect(host=host, port=port, user=user, password=password, dbname="postgres")
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()
        cur.execute(f"SELECT 1 FROM pg_database WHERE datname = %s", (dbname,))
        if not cur.fetchone():
            cur.execute(f'CREATE DATABASE "{dbname}"')
            logger.info(f"   ✅ Created database: {dbname}")
        else:
            logger.info(f"   ✅ Database exists: {dbname}")
        cur.close()
        conn.close()
    except psycopg2.OperationalError as e:
        logger.warning(f"   ⚠️ Could not check/create database: {e}")
        logger.info(f"   Attempting to connect directly to {dbname}...")


def load_to_postgres(
    df: pd.DataFrame,
    table_name: str,
    host=DEFAULT_HOST,
    port=DEFAULT_PORT,
    user=DEFAULT_USER,
    password=DEFAULT_PASSWORD,
    database=DEFAULT_DB,
    if_exists="replace",
    batch_size=5000,
):
    """Load dataframe into PostgreSQL."""
    logger.info(f"📤 LOAD: Writing {len(df)} rows to PostgreSQL...")
    logger.info(f"   Target: {host}:{port}/{database}.public.{table_name}")
    start = time.time()

    # Ensure database exists
    ensure_database(host, port, user, password, database)

    # Build connection string
    pw_part = f":{password}" if password else ""
    conn_str = f"postgresql://{user}{pw_part}@{host}:{port}/{database}"
    engine = create_engine(conn_str)

    # Load in batches
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists=if_exists,
        index=False,
        method="multi",
        chunksize=batch_size,
    )

    elapsed = time.time() - start
    logger.info(f"   ✅ Loaded {len(df)} rows in {elapsed:.2f}s")

    # Verify row count
    with engine.connect() as conn:
        result = conn.execute(text(f'SELECT COUNT(*) FROM "{table_name}"'))
        db_count = result.scalar()
        logger.info(f"   ✅ Verified: {db_count} rows in table '{table_name}'")

    # Show sample
    with engine.connect() as conn:
        result = conn.execute(text(f'SELECT * FROM "{table_name}" LIMIT 3'))
        sample = result.fetchall()
        logger.info(f"   📋 Sample rows:")
        for row in sample:
            logger.info(f"      {dict(row._mapping)}")

    return {
        "table": table_name,
        "database": database,
        "rows_loaded": len(df),
        "rows_verified": db_count,
        "elapsed_seconds": round(elapsed, 2),
    }


# ============================================================
# PHASE 5: GENERATE REPORT
# ============================================================
def generate_pipeline_report(extract_info, transform_info, quality_info, load_info):
    """Generate HTML pipeline execution report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    today = datetime.now().strftime("%Y%m%d")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ETL Pipeline Report — {timestamp}</title>
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family:'Segoe UI',system-ui,sans-serif; background:#f8fafc; color:#1e293b; padding:40px; }}
        .container {{ max-width:960px; margin:0 auto; }}
        .header {{ background:linear-gradient(135deg,#059669,#0d9488); color:white; padding:32px; border-radius:16px; margin-bottom:24px; }}
        .header h1 {{ font-size:24px; margin-bottom:8px; }}
        .header p {{ opacity:0.85; font-size:14px; }}
        .phase {{ background:white; padding:24px; border-radius:12px; box-shadow:0 1px 3px rgba(0,0,0,0.1); margin-bottom:16px; }}
        .phase h2 {{ font-size:18px; margin-bottom:12px; color:#059669; }}
        .metric {{ display:inline-block; background:#f0fdf4; padding:8px 16px; border-radius:8px; margin:4px; font-size:14px; }}
        .metric b {{ color:#059669; }}
        table {{ width:100%; border-collapse:collapse; margin-top:12px; }}
        th {{ background:#f1f5f9; padding:10px; text-align:left; font-size:13px; }}
        td {{ padding:10px; border-bottom:1px solid #e5e7eb; font-size:13px; }}
        .footer {{ text-align:center; margin-top:24px; font-size:12px; color:#94a3b8; }}
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🔄 ETL Pipeline Execution Report</h1>
        <p><b>Source:</b> {extract_info.get('source','')} → <b>Target:</b> {load_info.get('database','')}.{load_info.get('table','')} &nbsp;|&nbsp; <b>Timestamp:</b> {timestamp}</p>
    </div>

    <div class="phase">
        <h2>📥 Phase 1: Extract</h2>
        <div class="metric"><b>Source:</b> {extract_info.get('source','')}</div>
        <div class="metric"><b>File:</b> {extract_info.get('file','')}</div>
        <div class="metric"><b>Size:</b> {extract_info.get('size_mb',0):.2f} MB</div>
    </div>

    <div class="phase">
        <h2>🔄 Phase 2: Transform</h2>
        <div class="metric"><b>Rows:</b> {transform_info.get('rows',0)}</div>
        <div class="metric"><b>Columns:</b> {transform_info.get('columns',0)}</div>
        <div class="metric"><b>Dates Detected:</b> {transform_info.get('date_cols',0)}</div>
        <div class="metric"><b>Duplicates Removed:</b> {transform_info.get('dupes_removed',0)}</div>
    </div>

    <div class="phase">
        <h2>🔍 Phase 3: Quality</h2>
        <div class="metric"><b>Overall:</b> {quality_info.get('overall','')}</div>
        <table>
            <thead><tr><th>Check</th><th>Status</th><th>Details</th></tr></thead>
            <tbody>"""

    for c in quality_info.get("checks", []):
        icon = {"PASS": "✅", "FAIL": "❌", "WARN": "⚠️", "INFO": "ℹ️"}.get(c["status"], "")
        details = {k: v for k, v in c.items() if k not in ("check", "status")}
        html += f"<tr><td>{c['check']}</td><td>{icon} {c['status']}</td><td>{details}</td></tr>"

    html += f"""
            </tbody>
        </table>
    </div>

    <div class="phase">
        <h2>📤 Phase 4: Load</h2>
        <div class="metric"><b>Table:</b> {load_info.get('table','')}</div>
        <div class="metric"><b>Database:</b> {load_info.get('database','')}</div>
        <div class="metric"><b>Rows Loaded:</b> {load_info.get('rows_loaded',0)}</div>
        <div class="metric"><b>Verified:</b> {load_info.get('rows_verified',0)}</div>
        <div class="metric"><b>Time:</b> {load_info.get('elapsed_seconds',0)}s</div>
    </div>

    <div class="footer">
        Generated by Senior Data Engineer Skill • OpenClaw • {timestamp}
    </div>
</div>
</body>
</html>"""

    report_path = os.path.join(REPORT_DIR, f"etl_pipeline_report_{today}.html")
    os.makedirs(REPORT_DIR, exist_ok=True)
    with open(report_path, "w") as f:
        f.write(html)
    logger.info(f"📄 Pipeline report saved: {report_path}")
    return report_path


# ============================================================
# MAIN
# ============================================================
def main():
    parser = argparse.ArgumentParser(description="ETL Pipeline: Kaggle → PostgreSQL")
    parser.add_argument("--dataset", required=True, help="Kaggle dataset slug or local CSV path")
    parser.add_argument("--table", default="", help="Target table name (auto-derived if empty)")
    parser.add_argument("--database", default=DEFAULT_DB, help="PostgreSQL database name")
    parser.add_argument("--host", default=DEFAULT_HOST, help="PostgreSQL host")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="PostgreSQL port")
    parser.add_argument("--user", default=DEFAULT_USER, help="PostgreSQL user")
    parser.add_argument("--password", default=DEFAULT_PASSWORD, help="PostgreSQL password")
    parser.add_argument("--if-exists", default="replace", choices=["replace", "append", "fail"])
    parser.add_argument("--batch-size", type=int, default=5000)
    args = parser.parse_args()

    logger.info("=" * 60)
    logger.info("🚀 ETL PIPELINE: Kaggle → PostgreSQL")
    logger.info(f"   Dataset: {args.dataset}")
    logger.info("=" * 60)

    pipeline_start = time.time()

    # ---- EXTRACT ----
    csv_path = extract_from_kaggle(args.dataset)
    extract_info = {
        "source": args.dataset,
        "file": csv_path,
        "size_mb": os.path.getsize(csv_path) / 1024 / 1024,
    }

    # ---- READ CSV ----
    logger.info(f"📖 Reading CSV: {csv_path}")
    df = pd.read_csv(csv_path, low_memory=False)
    logger.info(f"   Shape: {df.shape}")

    # ---- TRANSFORM ----
    table_name = args.table or os.path.basename(csv_path).replace(".csv", "").replace("-", "_").lower()
    table_name = re.sub(r"[^a-z0-9_]", "", table_name)
    df = transform_data(df, table_name)
    transform_info = {
        "rows": len(df),
        "columns": len(df.columns),
        "date_cols": len(df.select_dtypes(include=["datetime64"]).columns),
        "dupes_removed": 0,
    }

    # ---- QUALITY CHECKS ----
    quality_info = run_quality_checks(df)

    # ---- LOAD ----
    load_info = load_to_postgres(
        df=df,
        table_name=table_name,
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        database=args.database,
        if_exists=args.if_exists,
        batch_size=args.batch_size,
    )

    # ---- REPORT ----
    report_path = generate_pipeline_report(extract_info, transform_info, quality_info, load_info)

    total_time = time.time() - pipeline_start
    logger.info("=" * 60)
    logger.info(f"✅ PIPELINE COMPLETE in {total_time:.2f}s")
    logger.info(f"   📊 {load_info['rows_loaded']} rows → {args.database}.{table_name}")
    logger.info(f"   📄 Report: {report_path}")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
