#!/usr/bin/env python3
"""
Data Quality Checker for customers-100.csv
Generated by Senior Data Engineer Skill
Date: 2026-03-16
"""

import csv
import re
import json
import sys
from datetime import datetime
from collections import Counter

# ============================================================
# CONFIGURATION
# ============================================================
INPUT_FILE = "/home/sindhuh/Downloads/customers-100.csv"
REPORT_DIR = "/home/sindhuh/.openclaw/workspace/reports"

EXPECTED_COLUMNS = [
    "Index", "Customer Id", "First Name", "Last Name", "Company",
    "City", "Country", "Phone 1", "Phone 2", "Email",
    "Subscription Date", "Website"
]

NOT_NULL_COLUMNS = [
    "Customer Id", "First Name", "Last Name", "Email",
    "Subscription Date", "Country"
]

UNIQUE_COLUMNS = ["Customer Id", "Email"]

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')
URL_REGEX = re.compile(r'^https?://[^\s]+$')
DATE_REGEX = re.compile(r'^\d{4}-\d{2}-\d{2}$')
CUSTOMER_ID_LENGTH = 15


# ============================================================
# QUALITY CHECKS
# ============================================================
def load_csv(filepath):
    """Load CSV and return rows + headers."""
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    return rows


def check_schema(rows, expected_columns):
    """Verify column names and order."""
    actual = list(rows[0].keys()) if rows else []
    missing = [c for c in expected_columns if c not in actual]
    extra = [c for c in actual if c not in expected_columns]
    return {
        "check": "schema_validation",
        "status": "PASS" if not missing and not extra else "FAIL",
        "expected_columns": len(expected_columns),
        "actual_columns": len(actual),
        "missing_columns": missing,
        "extra_columns": extra,
    }


def check_row_count(rows, min_rows=1, max_rows=1000000):
    """Verify row count is within expected range."""
    count = len(rows)
    return {
        "check": "row_count",
        "status": "PASS" if min_rows <= count <= max_rows else "FAIL",
        "row_count": count,
        "min_expected": min_rows,
        "max_expected": max_rows,
    }


def check_not_null(rows, columns):
    """Check for null/empty values in required columns."""
    results = []
    for col in columns:
        empty = [i+1 for i, r in enumerate(rows) if not r.get(col, "").strip()]
        results.append({
            "column": col,
            "status": "PASS" if not empty else "FAIL",
            "null_count": len(empty),
            "null_percentage": round(len(empty) / len(rows) * 100, 2),
            "sample_rows": empty[:5],
        })
    return {
        "check": "not_null",
        "status": "PASS" if all(r["status"] == "PASS" for r in results) else "FAIL",
        "details": results,
    }


def check_uniqueness(rows, columns):
    """Check for duplicate values in unique columns."""
    results = []
    for col in columns:
        values = [r.get(col, "") for r in rows]
        dupes = {v: c for v, c in Counter(values).items() if c > 1}
        results.append({
            "column": col,
            "status": "PASS" if not dupes else "FAIL",
            "duplicate_count": len(dupes),
            "duplicates": dict(list(dupes.items())[:5]),
        })
    return {
        "check": "uniqueness",
        "status": "PASS" if all(r["status"] == "PASS" for r in results) else "FAIL",
        "details": results,
    }


def check_email_format(rows):
    """Validate email format."""
    invalid = [(i+1, r["Email"]) for i, r in enumerate(rows)
               if not EMAIL_REGEX.match(r.get("Email", ""))]
    return {
        "check": "email_format",
        "status": "PASS" if not invalid else "FAIL",
        "invalid_count": len(invalid),
        "invalid_percentage": round(len(invalid) / len(rows) * 100, 2),
        "samples": invalid[:5],
    }


def check_url_format(rows):
    """Validate URL format."""
    invalid = [(i+1, r["Website"]) for i, r in enumerate(rows)
               if r.get("Website", "").strip() and not URL_REGEX.match(r["Website"])]
    return {
        "check": "url_format",
        "status": "PASS" if not invalid else "FAIL",
        "invalid_count": len(invalid),
        "samples": invalid[:5],
    }


def check_date_format(rows):
    """Validate date format (YYYY-MM-DD)."""
    invalid = []
    for i, r in enumerate(rows):
        d = r.get("Subscription Date", "")
        if not DATE_REGEX.match(d):
            invalid.append((i+1, d))
            continue
        try:
            datetime.strptime(d, "%Y-%m-%d")
        except ValueError:
            invalid.append((i+1, d))
    return {
        "check": "date_format",
        "status": "PASS" if not invalid else "FAIL",
        "invalid_count": len(invalid),
        "samples": invalid[:5],
    }


def check_phone_consistency(rows):
    """Analyze phone number format consistency."""
    formats = Counter()
    for r in rows:
        p = r.get("Phone 1", "")
        if p.startswith("+"):
            formats["international"] += 1
        elif p.startswith("001"):
            formats["001-prefix"] += 1
        elif "." in p:
            formats["dot-separated"] += 1
        elif "-" in p:
            formats["dash-separated"] += 1
        else:
            formats["plain"] += 1
    dominant = formats.most_common(1)[0] if formats else ("none", 0)
    consistency = round(dominant[1] / len(rows) * 100, 2) if rows else 0
    return {
        "check": "phone_consistency",
        "status": "PASS" if len(formats) <= 2 else "WARN",
        "formats_found": len(formats),
        "format_distribution": dict(formats),
        "dominant_format": dominant[0],
        "consistency_percentage": consistency,
    }


def check_customer_id_format(rows):
    """Validate Customer ID length and pattern."""
    invalid = [(i+1, r["Customer Id"]) for i, r in enumerate(rows)
               if len(r.get("Customer Id", "")) != CUSTOMER_ID_LENGTH]
    return {
        "check": "customer_id_format",
        "status": "PASS" if not invalid else "FAIL",
        "expected_length": CUSTOMER_ID_LENGTH,
        "invalid_count": len(invalid),
        "samples": invalid[:5],
    }


def check_freshness(rows):
    """Check data freshness based on Subscription Date."""
    dates = []
    for r in rows:
        try:
            dates.append(datetime.strptime(r["Subscription Date"], "%Y-%m-%d"))
        except (ValueError, KeyError):
            pass
    if not dates:
        return {"check": "freshness", "status": "FAIL", "reason": "no valid dates"}
    latest = max(dates)
    oldest = min(dates)
    return {
        "check": "freshness",
        "status": "INFO",
        "latest_record": latest.strftime("%Y-%m-%d"),
        "oldest_record": oldest.strftime("%Y-%m-%d"),
        "date_range_days": (latest - oldest).days,
    }


# ============================================================
# REPORT GENERATION
# ============================================================
def generate_html_report(report, output_path):
    """Generate styled HTML report."""
    checks = report["checks"]
    total = len(checks)
    passed = sum(1 for c in checks if c["status"] == "PASS")
    warned = sum(1 for c in checks if c["status"] == "WARN")
    failed = sum(1 for c in checks if c["status"] == "FAIL")
    info = sum(1 for c in checks if c["status"] == "INFO")

    def status_badge(s):
        colors = {"PASS": "#22c55e", "FAIL": "#ef4444", "WARN": "#f59e0b", "INFO": "#3b82f6"}
        return f'<span style="background:{colors.get(s,"#6b7280")};color:white;padding:3px 10px;border-radius:12px;font-size:13px;font-weight:600">{s}</span>'

    rows_html = ""
    for c in checks:
        name = c["check"].replace("_", " ").title()
        details = ""
        for k, v in c.items():
            if k in ("check", "status"):
                continue
            if isinstance(v, list) and len(v) > 3:
                v = v[:3]
            details += f"<b>{k}</b>: {v}<br>"
        rows_html += f"""
        <tr>
            <td style="padding:12px;border-bottom:1px solid #e5e7eb;font-weight:500">{name}</td>
            <td style="padding:12px;border-bottom:1px solid #e5e7eb;text-align:center">{status_badge(c['status'])}</td>
            <td style="padding:12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#4b5563">{details}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Quality Report — {report['file']}</title>
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family:'Segoe UI',system-ui,-apple-system,sans-serif; background:#f8fafc; color:#1e293b; padding:40px; }}
        .container {{ max-width:960px; margin:0 auto; }}
        .header {{ background:linear-gradient(135deg,#1e40af,#7c3aed); color:white; padding:32px; border-radius:16px; margin-bottom:24px; }}
        .header h1 {{ font-size:24px; margin-bottom:8px; }}
        .header p {{ opacity:0.85; font-size:14px; }}
        .summary {{ display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-bottom:24px; }}
        .card {{ background:white; padding:20px; border-radius:12px; box-shadow:0 1px 3px rgba(0,0,0,0.1); text-align:center; }}
        .card .num {{ font-size:32px; font-weight:700; }}
        .card .label {{ font-size:13px; color:#6b7280; margin-top:4px; }}
        .pass .num {{ color:#22c55e; }} .fail .num {{ color:#ef4444; }}
        .warn .num {{ color:#f59e0b; }} .info .num {{ color:#3b82f6; }}
        table {{ width:100%; background:white; border-radius:12px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,0.1); }}
        th {{ background:#f1f5f9; padding:14px; text-align:left; font-size:13px; text-transform:uppercase; color:#64748b; }}
        .footer {{ text-align:center; margin-top:24px; font-size:12px; color:#94a3b8; }}
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>📊 Data Quality Report</h1>
        <p><b>File:</b> {report['file']} &nbsp;|&nbsp; <b>Rows:</b> {report['row_count']} &nbsp;|&nbsp; <b>Columns:</b> {report['column_count']} &nbsp;|&nbsp; <b>Generated:</b> {report['timestamp']}</p>
    </div>

    <div class="summary">
        <div class="card pass"><div class="num">{passed}</div><div class="label">Passed</div></div>
        <div class="card fail"><div class="num">{failed}</div><div class="label">Failed</div></div>
        <div class="card warn"><div class="num">{warned}</div><div class="label">Warnings</div></div>
        <div class="card info"><div class="num">{info}</div><div class="label">Info</div></div>
    </div>

    <table>
        <thead><tr><th>Check</th><th style="text-align:center">Status</th><th>Details</th></tr></thead>
        <tbody>{rows_html}</tbody>
    </table>

    <div class="footer">
        Generated by Senior Data Engineer Skill • OpenClaw • {report['timestamp']}
    </div>
</div>
</body>
</html>"""

    with open(output_path, 'w') as f:
        f.write(html)
    return output_path


# ============================================================
# MAIN
# ============================================================
def main():
    filepath = sys.argv[1] if len(sys.argv) > 1 else INPUT_FILE
    print(f"🔍 Running data quality checks on: {filepath}")
    print("=" * 60)

    rows = load_csv(filepath)

    checks = [
        check_schema(rows, EXPECTED_COLUMNS),
        check_row_count(rows, min_rows=1, max_rows=1000000),
        check_not_null(rows, NOT_NULL_COLUMNS),
        check_uniqueness(rows, UNIQUE_COLUMNS),
        check_email_format(rows),
        check_url_format(rows),
        check_date_format(rows),
        check_phone_consistency(rows),
        check_customer_id_format(rows),
        check_freshness(rows),
    ]

    report = {
        "file": filepath,
        "row_count": len(rows),
        "column_count": len(rows[0].keys()) if rows else 0,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "checks": checks,
    }

    # Print results
    for c in checks:
        icon = {"PASS": "✅", "FAIL": "❌", "WARN": "⚠️", "INFO": "ℹ️"}.get(c["status"], "❓")
        print(f"  {icon} {c['check'].replace('_',' ').title()}: {c['status']}")

    passed = sum(1 for c in checks if c["status"] == "PASS")
    total = len(checks)
    print(f"\n{'=' * 60}")
    print(f"📊 Overall: {passed}/{total} checks passed")

    # Generate HTML report
    today = datetime.now().strftime("%Y%m%d")
    filename = filepath.split("/")[-1].replace(".csv", "")
    html_path = f"{REPORT_DIR}/{filename}_quality_report_{today}.html"
    generate_html_report(report, html_path)
    print(f"📄 HTML Report saved: {html_path}")

    # Save JSON report
    json_path = f"{REPORT_DIR}/{filename}_quality_report_{today}.json"
    with open(json_path, 'w') as f:
        json.dump(report, f, indent=2, default=str)
    print(f"📋 JSON Report saved: {json_path}")

    return report


if __name__ == "__main__":
    main()
